### ISSUE TITLE
Connect all media queries to CSS variable breakpoints

### ISSUE THREAD

**Issue by kylemh** [OperationCode/front-end#292]
# Feature request
**Is your feature request related to a problem? Please describe.**
There exist a large slew of hard-coded viewport checks within media queries around our stylesheets. Hard-coding isn't reuse. It's difficult to refactor, and prone to developer mistakes.

**Describe the solution you'd like**
Now that we have breakpoints defined via `common/styles/variables`, I'd like them leveraged so that we have a manageable system of media queries. 

**Example:**
```globalStyles.css```
```css
/* @media screen and (max-width: 480px) { */
@media screen and (max-width: var(--smallViewportWidth)) {
  html {
    .font-size: 14px !important;
  }
}

/* @media screen and (min-width: 481px) and (max-width: 960px) { */
@media screen and (min-width: var(--smallViewportWidth)) and (max-width: var(--largeViewportWidth)) {
  html {
    font-size: 16px !important;
  }
}
```

**Describe alternatives you've considered**

**Additional context**
You may notice visual regression as you go. This is okay. We need to make a certain amount of changes before we attempt to tackle the various style issues on the website. Just change the code, and document this issues in your PR please 🙏
